"""added column name

Revision ID: 107a4e6ff1a8
Revises: 90bbe50142c5
Create Date: 2025-12-11 10:56:47.425746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107a4e6ff1a8'
down_revision: Union[str, Sequence[str], None] = '90bbe50142c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_table', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummy_table', 'name')
    # ### end Alembic commands ###
