"""added state and other filled

Revision ID: 239e7ee3ddd0
Revises: d09290cb65f0
Create Date: 2025-11-20 11:06:40.570055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239e7ee3ddd0'
down_revision: Union[str, Sequence[str], None] = 'd09290cb65f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perdix_mp_project_drafts', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('ward', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('ward', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perdix_mp_projects', 'ward')
    op.drop_column('perdix_mp_projects', 'city')
    op.drop_column('perdix_mp_projects', 'state')
    op.drop_column('perdix_mp_project_drafts', 'ward')
    op.drop_column('perdix_mp_project_drafts', 'city')
    op.drop_column('perdix_mp_project_drafts', 'state')
    # ### end Alembic commands ###
