"""added the status

Revision ID: 44108aea6705
Revises: ead42300f6a4
Create Date: 2025-12-11 11:17:49.891112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44108aea6705'
down_revision: Union[str, Sequence[str], None] = 'ead42300f6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_table', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummy_table', 'quantity')
    # ### end Alembic commands ###
