"""added the status

Revision ID: a3adeb2a3234
Revises: bdac68edc2f2
Create Date: 2025-12-11 11:16:14.813820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3adeb2a3234'
down_revision: Union[str, Sequence[str], None] = 'bdac68edc2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_table', sa.Column('status', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummy_table', 'status')
    # ### end Alembic commands ###
