"""added column desc

Revision ID: bdac68edc2f2
Revises: 107a4e6ff1a8
Create Date: 2025-12-11 10:57:58.372651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdac68edc2f2'
down_revision: Union[str, Sequence[str], None] = '107a4e6ff1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_table', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummy_table', 'description')
    # ### end Alembic commands ###
