"""add contact details field

Revision ID: d09290cb65f0
Revises: c130d86e4493
Create Date: 2025-11-20 10:37:03.457531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09290cb65f0'
down_revision: Union[str, Sequence[str], None] = 'c130d86e4493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perdix_mp_project_drafts', sa.Column('contact_person_designation', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('contact_person_email', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('contact_person_phone', sa.String(length=50), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('contact_person_designation', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('contact_person_email', sa.String(length=255), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('contact_person_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perdix_mp_projects', 'contact_person_phone')
    op.drop_column('perdix_mp_projects', 'contact_person_email')
    op.drop_column('perdix_mp_projects', 'contact_person_designation')
    op.drop_column('perdix_mp_project_drafts', 'contact_person_phone')
    op.drop_column('perdix_mp_project_drafts', 'contact_person_email')
    op.drop_column('perdix_mp_project_drafts', 'contact_person_designation')
    # ### end Alembic commands ###
