"""added the age

Revision ID: ead42300f6a4
Revises: a3adeb2a3234
Create Date: 2025-12-11 11:17:21.850896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead42300f6a4'
down_revision: Union[str, Sequence[str], None] = 'a3adeb2a3234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_table', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummy_table', 'age')
    # ### end Alembic commands ###
