"""add_project_drafts_table

Revision ID: ef16018892ed
Revises: d49f271cf991
Create Date: 2025-11-18 17:52:09.287226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef16018892ed'
down_revision: Union[str, Sequence[str], None] = 'd49f271cf991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perdix_mp_project_drafts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_type', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('project_stage', sa.String(length=50), server_default='planning', nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_project_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('funding_requirement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('already_secured_funds', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=True),
    sa.Column('fundraising_start_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fundraising_end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('municipality_credit_rating', sa.String(length=20), nullable=True),
    sa.Column('municipality_credit_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('visibility', sa.String(length=50), server_default='private', nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('last_saved_tab', sa.String(length=50), nullable=True),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint("project_stage IN ('planning', 'initiated', 'in_progress')", name='check_draft_project_stage'),
    sa.CheckConstraint("visibility IN ('private', 'public')", name='check_draft_visibility'),
    sa.CheckConstraint('completion_percentage >= 0 AND completion_percentage <= 100', name='check_completion_percentage'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perdix_mp_project_drafts_id'), 'perdix_mp_project_drafts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perdix_mp_project_drafts_id'), table_name='perdix_mp_project_drafts')
    op.drop_table('perdix_mp_project_drafts')
    # ### end Alembic commands ###
